### ISSUE TITLE
单元测试script.py报错

### ISSUE THREAD

**Issue by likidu** [meowlab/shadowsocks-nacl#2]
正在做一个小应用想集成nacl版本的shadowsocks。

### Env

* `python`: `2.7.15`
* `chromedriver`: `2.4.6`
* `chrome`: `72.0`

Chrome使用Web Server extension加载整个`shadowsocks-nacl`目录到`localhost:6001`下。

`pnacl`使用nacl_sdk pepper_49编译通过。

### Steps

运行 `python script.py` 后报错:

```bash
Preparing webdriver...
Initializing test...
[]
Traceback (most recent call last):
  File "script.py", line 158, in <module>
    if not test():
  File "script.py", line 154, in test
    raise e
TypeError: cannot concatenate 'str' and 'dict' objects
```

求教是否环境设置有问题？

**Comment by nekolab** [comment]
Hi
你可以把脚本里的`init_result`打印出来看一下，可能返回的错误是个字典所以导致脚本运行失败
